version: '2.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wlxjury
      MYSQL_USER: wlxjury_user
      MYSQL_PASSWORD: wlxjury_password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  wlxjury:
    image: wlxjury:0.11-SNAPSHOT
    environment:
      WLXJURY_DB_HOST: db
      WLXJURY_DB: wlxjury
      WLXJURY_DB_USER: wlxjury_user
      WLXJURY_DB_PASSWORD: wlxjury_password
      JAVA_OPTS: -Ddb.default.migration.auto=true -Dplay.http.secret.key=realSecret
    ports:
      - "9000:9000"

    depends_on:
      db:
        condition: service_healthy